# This contains configuration values needed for the tools provided by
# the `anaconda-packaging-utils` project.
token:
  # Generate a token, following the GitHub docs:
  #   https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token
  # TODO determine permissions
  github: TODO
local_path:
  # Full path to your local copy of the `aggregate` repository
  aggregate: TODO
