# This contains configuration values needed for the tools provided by
# the `anaconda-packaging-utils` project.
token:
  # Used for the GitHubApi module
  # Generate a token, following the GitHub docs:
  #   https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token
  # TODO determine permissions
  github: TODO
  # Used for the JiraApi module. Instructions can be found here:
  #   https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/
  jira: TODO
user_info:
  # Work email address used for SSO apps
  email: TODO
local_path:
  # Full path to your local copy of the `aggregate` repository
  aggregate: TODO
