name: anaconda_packaging_utils

dependencies:
  # Python/plugins
  - black
  - isort
  - mypy
  - python=3.11
  - pytest
  - pytest-cov
  - pytest-xdist
  - pylint
  - pip
  # Python libraries
  - click>=8.1.7
  - jinja2
  - conda-forge::jsonschema
  - conda-forge::types-jsonschema
  - percy>=0.1.1
  - PyGithub
  - conda-forge::pyyaml
  - conda-forge::types-pyyaml
  - requests
  - types-requests
  # Other
  - conda
  - conda-build
  - pre-commit
