name: anaconda_packaging_utils

dependencies:
  # Python/plugins
  - black
  - isort
  - mypy
  - python >=3.11
  - pytest
  - pytest-cov
  - pytest-xdist
  - pylint
  - pip
  # Python libraries
  - jsonschema
  - types-jsonschema
  - distro-tooling::percy >=0.1.3
  - PyGithub
  - jira >=3.6.0
  - pyyaml
  - types-pyyaml
  - requests
  - types-requests
  # Other
  - conda
  - conda-build
  - pre-commit
  - make
