on:
  push:
    branches:
      - main
  pull_request:

name: Code Checks

jobs:
  # NOTE: Tests run via `pre-commit` on 3.11; All other versions of Python run just the tests.
  pre-commit:
      name: Run pre-commit on 3.11
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: ./.github/actions/setup-env
          with:
            python-version: "3.11"
        - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
  test:
      runs-on: ubuntu-latest
      name: Test on ${{ matrix.python-version }}
      strategy:
        matrix:
          python-version: ["3.8", "3.9", "3.10"]
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        - uses: ./.github/actions/setup-env
          with:
            python-version: ${{ matrix.python-version }}
        - run: |
            make test
